spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://yonombara.cloyi6mws20s.ap-northeast-2.rds.amazonaws.com:3306/yonombara
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yonombara
    password: yonombara

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 3
  refresh-token:
    plus-hour: 12